
package com.hp.schemas.sm._7;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProblemManagement", targetNamespace = "http://schemas.hp.com/SM/7", wsdlLocation = "http://10.4.50.192:13083/SM/7/ProblemManagement?wsdl")
public class ProblemManagement_Service extends Service
{

    private final static URL PROBLEMMANAGEMENT_WSDL_LOCATION;
    private final static WebServiceException PROBLEMMANAGEMENT_EXCEPTION;
    private final static QName PROBLEMMANAGEMENT_QNAME = new QName("http://schemas.hp.com/SM/7", "ProblemManagement");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("http://localhost:8084/ProblemManagement?wsdl");
            url = new URL("http://10.4.50.192:13083/SM/7/ProblemManagement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROBLEMMANAGEMENT_WSDL_LOCATION = url;
        PROBLEMMANAGEMENT_EXCEPTION = e;
    }

    public ProblemManagement_Service() {
        super(__getWsdlLocation(), PROBLEMMANAGEMENT_QNAME);
    }

    public ProblemManagement_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROBLEMMANAGEMENT_QNAME, features);
    }

    public ProblemManagement_Service(URL wsdlLocation) {
        super(wsdlLocation, PROBLEMMANAGEMENT_QNAME);
    }

    public ProblemManagement_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROBLEMMANAGEMENT_QNAME, features);
    }

    public ProblemManagement_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProblemManagement_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProblemManagement
     */
    @WebEndpoint(name = "ProblemManagement")
    public ProblemManagement getProblemManagement() {
        return super.getPort(new QName("http://schemas.hp.com/SM/7", "ProblemManagement"), ProblemManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProblemManagement
     */
    @WebEndpoint(name = "ProblemManagement")
    public ProblemManagement getProblemManagement(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.hp.com/SM/7", "ProblemManagement"), ProblemManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROBLEMMANAGEMENT_EXCEPTION!= null) {
            throw PROBLEMMANAGEMENT_EXCEPTION;
        }
        return PROBLEMMANAGEMENT_WSDL_LOCATION;
    }

}
