
package com.hp.schemas.sm._7;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProblemManagement", targetNamespace = "http://schemas.hp.com/SM/7")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.hp.schemas.sm._7.ObjectFactory.class,
    com.hp.schemas.sm._7.common.ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class
})
public interface ProblemManagement {


    /**
     * 
     * @param retrieveNEW9330035ProblemRequest
     * @return
     *     returns com.hp.schemas.sm._7.RetrieveNEW9330035ProblemResponse
     */
    @WebMethod(operationName = "RetrieveNEW9.33.0035Problem", action = "Retrieve")
    @WebResult(name = "RetrieveNEW9.33.0035ProblemResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveNEW9.33.0035ProblemResponse")
    public RetrieveNEW9330035ProblemResponse retrieveNEW9330035Problem(
        @WebParam(name = "RetrieveNEW9.33.0035ProblemRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveNEW9.33.0035ProblemRequest")
        RetrieveNEW9330035ProblemRequest retrieveNEW9330035ProblemRequest);

    /**
     * 
     * @param retrieveNEW9330035ProblemKeysListRequest
     * @return
     *     returns com.hp.schemas.sm._7.RetrieveNEW9330035ProblemKeysListResponse
     */
    @WebMethod(operationName = "RetrieveNEW9.33.0035ProblemKeysList", action = "RetrieveKeysList")
    @WebResult(name = "RetrieveNEW9.33.0035ProblemKeysListResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveNEW9.33.0035ProblemKeysListResponse")
    public RetrieveNEW9330035ProblemKeysListResponse retrieveNEW9330035ProblemKeysList(
        @WebParam(name = "RetrieveNEW9.33.0035ProblemKeysListRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveNEW9.33.0035ProblemKeysListRequest")
        RetrieveNEW9330035ProblemKeysListRequest retrieveNEW9330035ProblemKeysListRequest);

    /**
     * 
     * @param retrieveNEW9330035ProblemListRequest
     * @return
     *     returns com.hp.schemas.sm._7.RetrieveNEW9330035ProblemListResponse
     */
    @WebMethod(operationName = "RetrieveNEW9.33.0035ProblemList", action = "RetrieveList")
    @WebResult(name = "RetrieveNEW9.33.0035ProblemListResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveNEW9.33.0035ProblemListResponse")
    public RetrieveNEW9330035ProblemListResponse retrieveNEW9330035ProblemList(
        @WebParam(name = "RetrieveNEW9.33.0035ProblemListRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveNEW9.33.0035ProblemListRequest")
        RetrieveNEW9330035ProblemListRequest retrieveNEW9330035ProblemListRequest);

    /**
     * 
     * @param updateNEW9330035ProblemRequest
     * @return
     *     returns com.hp.schemas.sm._7.UpdateNEW9330035ProblemResponse
     */
    @WebMethod(operationName = "UpdateNEW9.33.0035Problem", action = "Update")
    @WebResult(name = "UpdateNEW9.33.0035ProblemResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "UpdateNEW9.33.0035ProblemResponse")
    public UpdateNEW9330035ProblemResponse updateNEW9330035Problem(
        @WebParam(name = "UpdateNEW9.33.0035ProblemRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "UpdateNEW9.33.0035ProblemRequest")
        UpdateNEW9330035ProblemRequest updateNEW9330035ProblemRequest);

    /**
     * 
     * @param closeNEW9330035ProblemRequest
     * @return
     *     returns com.hp.schemas.sm._7.CloseNEW9330035ProblemResponse
     */
    @WebMethod(operationName = "CloseNEW9.33.0035Problem", action = "Close")
    @WebResult(name = "CloseNEW9.33.0035ProblemResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CloseNEW9.33.0035ProblemResponse")
    public CloseNEW9330035ProblemResponse closeNEW9330035Problem(
        @WebParam(name = "CloseNEW9.33.0035ProblemRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CloseNEW9.33.0035ProblemRequest")
        CloseNEW9330035ProblemRequest closeNEW9330035ProblemRequest);

    /**
     * 
     * @param cloneNEW9330035ProblemRequest
     * @return
     *     returns com.hp.schemas.sm._7.CloneNEW9330035ProblemResponse
     */
    @WebMethod(operationName = "CloneNEW9.33.0035Problem", action = "Clone")
    @WebResult(name = "CloneNEW9.33.0035ProblemResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CloneNEW9.33.0035ProblemResponse")
    public CloneNEW9330035ProblemResponse cloneNEW9330035Problem(
        @WebParam(name = "CloneNEW9.33.0035ProblemRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CloneNEW9.33.0035ProblemRequest")
        CloneNEW9330035ProblemRequest cloneNEW9330035ProblemRequest);

    /**
     * 
     * @param createNEW9330035ProblemRequest
     * @return
     *     returns com.hp.schemas.sm._7.CreateNEW9330035ProblemResponse
     */
    @WebMethod(operationName = "CreateNEW9.33.0035Problem", action = "Create")
    @WebResult(name = "CreateNEW9.33.0035ProblemResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CreateNEW9.33.0035ProblemResponse")
    public CreateNEW9330035ProblemResponse createNEW9330035Problem(
        @WebParam(name = "CreateNEW9.33.0035ProblemRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CreateNEW9.33.0035ProblemRequest")
        CreateNEW9330035ProblemRequest createNEW9330035ProblemRequest);

    /**
     * 
     * @param retrieveProblemRequest
     * @return
     *     returns com.hp.schemas.sm._7.RetrieveProblemResponse
     */
    @WebMethod(operationName = "RetrieveProblem", action = "Retrieve")
    @WebResult(name = "RetrieveProblemResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveProblemResponse")
    public RetrieveProblemResponse retrieveProblem(
        @WebParam(name = "RetrieveProblemRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveProblemRequest")
        RetrieveProblemRequest retrieveProblemRequest);

    /**
     * 
     * @param retrieveProblemKeysListRequest
     * @return
     *     returns com.hp.schemas.sm._7.RetrieveProblemKeysListResponse
     */
    @WebMethod(operationName = "RetrieveProblemKeysList", action = "RetrieveKeysList")
    @WebResult(name = "RetrieveProblemKeysListResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveProblemKeysListResponse")
    public RetrieveProblemKeysListResponse retrieveProblemKeysList(
        @WebParam(name = "RetrieveProblemKeysListRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveProblemKeysListRequest")
        RetrieveProblemKeysListRequest retrieveProblemKeysListRequest);

    /**
     * 
     * @param retrieveProblemListRequest
     * @return
     *     returns com.hp.schemas.sm._7.RetrieveProblemListResponse
     */
    @WebMethod(operationName = "RetrieveProblemList", action = "RetrieveList")
    @WebResult(name = "RetrieveProblemListResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveProblemListResponse")
    public RetrieveProblemListResponse retrieveProblemList(
        @WebParam(name = "RetrieveProblemListRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveProblemListRequest")
        RetrieveProblemListRequest retrieveProblemListRequest);

    /**
     * 
     * @param updateProblemRequest
     * @return
     *     returns com.hp.schemas.sm._7.UpdateProblemResponse
     */
    @WebMethod(operationName = "UpdateProblem", action = "Update")
    @WebResult(name = "UpdateProblemResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "UpdateProblemResponse")
    public UpdateProblemResponse updateProblem(
        @WebParam(name = "UpdateProblemRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "UpdateProblemRequest")
        UpdateProblemRequest updateProblemRequest);

    /**
     * 
     * @param closeProblemRequest
     * @return
     *     returns com.hp.schemas.sm._7.CloseProblemResponse
     */
    @WebMethod(operationName = "CloseProblem", action = "Close")
    @WebResult(name = "CloseProblemResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CloseProblemResponse")
    public CloseProblemResponse closeProblem(
        @WebParam(name = "CloseProblemRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CloseProblemRequest")
        CloseProblemRequest closeProblemRequest);

    /**
     * 
     * @param cloneProblemRequest
     * @return
     *     returns com.hp.schemas.sm._7.CloneProblemResponse
     */
    @WebMethod(operationName = "CloneProblem", action = "Clone")
    @WebResult(name = "CloneProblemResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CloneProblemResponse")
    public CloneProblemResponse cloneProblem(
        @WebParam(name = "CloneProblemRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CloneProblemRequest")
        CloneProblemRequest cloneProblemRequest);

    /**
     * 
     * @param createProblemRequest
     * @return
     *     returns com.hp.schemas.sm._7.CreateProblemResponse
     */
    @WebMethod(operationName = "CreateProblem", action = "Create")
    @WebResult(name = "CreateProblemResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CreateProblemResponse")
    public CreateProblemResponse createProblem(
        @WebParam(name = "CreateProblemRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CreateProblemRequest")
        CreateProblemRequest createProblemRequest);

    /**
     * 
     * @param retrieveProblemTaskRequest
     * @return
     *     returns com.hp.schemas.sm._7.RetrieveProblemTaskResponse
     */
    @WebMethod(operationName = "RetrieveProblemTask", action = "Retrieve")
    @WebResult(name = "RetrieveProblemTaskResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveProblemTaskResponse")
    public RetrieveProblemTaskResponse retrieveProblemTask(
        @WebParam(name = "RetrieveProblemTaskRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveProblemTaskRequest")
        RetrieveProblemTaskRequest retrieveProblemTaskRequest);

    /**
     * 
     * @param retrieveProblemTaskKeysListRequest
     * @return
     *     returns com.hp.schemas.sm._7.RetrieveProblemTaskKeysListResponse
     */
    @WebMethod(operationName = "RetrieveProblemTaskKeysList", action = "RetrieveKeysList")
    @WebResult(name = "RetrieveProblemTaskKeysListResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveProblemTaskKeysListResponse")
    public RetrieveProblemTaskKeysListResponse retrieveProblemTaskKeysList(
        @WebParam(name = "RetrieveProblemTaskKeysListRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveProblemTaskKeysListRequest")
        RetrieveProblemTaskKeysListRequest retrieveProblemTaskKeysListRequest);

    /**
     * 
     * @param retrieveProblemTaskListRequest
     * @return
     *     returns com.hp.schemas.sm._7.RetrieveProblemTaskListResponse
     */
    @WebMethod(operationName = "RetrieveProblemTaskList", action = "RetrieveList")
    @WebResult(name = "RetrieveProblemTaskListResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveProblemTaskListResponse")
    public RetrieveProblemTaskListResponse retrieveProblemTaskList(
        @WebParam(name = "RetrieveProblemTaskListRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveProblemTaskListRequest")
        RetrieveProblemTaskListRequest retrieveProblemTaskListRequest);

    /**
     * 
     * @param createProblemTaskRequest
     * @return
     *     returns com.hp.schemas.sm._7.CreateProblemTaskResponse
     */
    @WebMethod(operationName = "CreateProblemTask", action = "Create")
    @WebResult(name = "CreateProblemTaskResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CreateProblemTaskResponse")
    public CreateProblemTaskResponse createProblemTask(
        @WebParam(name = "CreateProblemTaskRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CreateProblemTaskRequest")
        CreateProblemTaskRequest createProblemTaskRequest);

    /**
     * 
     * @param updateProblemTaskRequest
     * @return
     *     returns com.hp.schemas.sm._7.UpdateProblemTaskResponse
     */
    @WebMethod(operationName = "UpdateProblemTask", action = "Update")
    @WebResult(name = "UpdateProblemTaskResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "UpdateProblemTaskResponse")
    public UpdateProblemTaskResponse updateProblemTask(
        @WebParam(name = "UpdateProblemTaskRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "UpdateProblemTaskRequest")
        UpdateProblemTaskRequest updateProblemTaskRequest);

    /**
     * 
     * @param closeProblemTaskRequest
     * @return
     *     returns com.hp.schemas.sm._7.CloseProblemTaskResponse
     */
    @WebMethod(operationName = "CloseProblemTask", action = "Close")
    @WebResult(name = "CloseProblemTaskResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CloseProblemTaskResponse")
    public CloseProblemTaskResponse closeProblemTask(
        @WebParam(name = "CloseProblemTaskRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CloseProblemTaskRequest")
        CloseProblemTaskRequest closeProblemTaskRequest);

    /**
     * 
     * @param cancelProblemTaskRequest
     * @return
     *     returns com.hp.schemas.sm._7.CancelProblemTaskResponse
     */
    @WebMethod(operationName = "CancelProblemTask", action = "Cancel")
    @WebResult(name = "CancelProblemTaskResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CancelProblemTaskResponse")
    public CancelProblemTaskResponse cancelProblemTask(
        @WebParam(name = "CancelProblemTaskRequest", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CancelProblemTaskRequest")
        CancelProblemTaskRequest cancelProblemTaskRequest);

}
